Add Monitoring coreos.com custom resources to the scheme
When Prometheus Redpanda helm chart dependency is enabled, then DecodeYAMLFrom
is not working due to missing ServiceMonitor custom resource in scheme.
```
=== CONT  TestConfigMap/14-prometheus-no-tls-values.yaml
    chart_test.go:182:
        	Error Trace:	/Users/rafalkorepta/workspace/redpanda/helm-charts/charts/redpanda/chart_test.go:182
        	Error:      	Received unexpected error:
        	            	no kind "ServiceMonitor" is registered for version "monitoring.coreos.com/v1" in scheme "pkg/runtime/scheme.go:100"
        	Test:       	TestConfigMap/14-prometheus-no-tls-values.yaml
    --- FAIL: TestConfigMap/14-prometheus-no-tls-values.yaml (0.08s)
```