Move git configuration to earlier step
Due to error in https://github.com/redpanda-data/helm-charts/actions/runs/8708200936/job/23884992632#step:7:109
the git configuration is performed just after checkout.

Reference

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az1245-596.44uquw3knzoenloncamig1c14h.dx.internal.cloudapp.net>) not allowed
Error: exit status 128
Usage:
  cr index [flags]
```